apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - external-audiobooks.yaml
  - external-jellyfin.yaml
  - external-paperless.yaml
  - external-harbor.yaml
  - stackrox.yaml
  
patches:
  - path: wildcard-tls-patch.yaml