apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: stackrox-central-tls
  namespace: stackrox
spec:
  commonName: stackrox.home-k8s.sigurs.io
  secretName: stackrox-central-tls
  dnsNames: 
    - stackrox.home-k8s.sigurs.io
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: central-transport
  namespace: stackrox
spec:
  insecureSkipVerify: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stackrox-central
  namespace: stackrox
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/service.serverstransport: stackrox-central-transport@kubernetescrd
spec:
  tls:
    - hosts:
        - stackrox.home-k8s.sigurs.io
      secretName: stackrox-central-tls
  rules:
    - host: stackrox.home-k8s.sigurs.io
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: central
              port:
                number: 443