apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: stackrox-central-tls
  namespace: stackrox
spec:
  commonName: stackrox.home-k8s.sigurs.io
  secretName: stackrox-central-tls
  dnsNames: 
    - stackrox.home-k8s.sigurs.io
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: central-ingress
  namespace: stackrox
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`stackrox.home-k8s.sigurs.io`)
      kind: Rule
      services:
        - name: central
          port: 443
          scheme: https
          serversTransport: central-transport
  tls:
    secretName: stackrox-central-tls  # your TLS cert
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: central-transport
  namespace: stackrox
spec:
  insecureSkipVerify: true  # skip verification of Central's internal cert