apiVersion: apps/v1
kind: Deployment
metadata:
  name: searxng
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: searxng
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: searxng
    spec:
      automountServiceAccountToken: false
      hostUsers: false
      containers:
        - name: container
          image: ghcr.io/searxng/searxng:2026.2.20-93ac6ceb3@sha256:1d42b843667db5b004e5d2b7aef3fc4ed921555da9e89acbb6c8d3a6f0d807c6
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          env:
            - name: SEARXNG_BASE_URL
              value: "https://search.sigurs.io"

            # Security
            - name: SEARXNG_SECRET
              valueFrom:
                secretKeyRef:
                  name: searxng
                  key: SEARXNG_SECRET

            - name: TZ
              value: Europe/Helsinki
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: searxng
              mountPath: /etc/searxng
              subPath: etc/searxng
            - name: searxng
              mountPath: /var/cache/searxng
              subPath: var/cache/searxng
      volumes:
        - name: searxng
          persistentVolumeClaim:
            claimName: searxng