apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: open-webui
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: open-webui
    spec:
      automountServiceAccountToken: false
      hostUsers: false
      containers:
        - name: open-webui
          image: ghcr.io/open-webui/open-webui:v0.8.3@sha256:0558a1b498dbfbf469d9a94866e2892275c7d1ef4d96894cf0b31d657d44bc55
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          env:
            # Enable offline mode
            - name: OFFLINE_MODE
              value: "true"
            - name: HF_HUB_OFFLINE
              value: "1"

            # Security
            - name: WEBUI_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: open-webui
                  key: WEBUI_SECRET_KEY
            - name: CORS_ALLOW_ORIGIN
              value: "https://chat.sigurs.io"
            
            # Database
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: open-webui
                  key: DATABASE_URL

            # Vector DB
            - name: VECTOR_DB
              value: pgvector
            - name: PGVECTOR_CREATE_EXTENSION
              value: "false"
            - name: PGVECTOR_DB_URL
              valueFrom:
                secretKeyRef:
                  name: open-webui
                  key: PGVECTOR_DB_URL

            - name: TZ
              value: Europe/Helsinki
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: open-webui
              mountPath: /app/backend/data
              subPath: app/backend/data
        - name: apache-tika
          image: apache/tika:3.2.3.0-full@sha256:4bdb20f20b3d08d46f8da3e95fdf7a71d74b4e6e0728b99a870a6f19633803d5
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 9998
              name: tika
      volumes:
        - name: open-webui
          persistentVolumeClaim:
            claimName: open-webui