# # Don't terminate TLS at ArgoCD
# configs:
#   params:
#     server.insecure: true

# # Enable creation of ingress resource
# server:
#   ingress:
#     enabled: true

# # For demo, delete CRDs if uninstalled.
# crds:
#   keep: false

ipam:
  operator:
    clusterPoolIPv4PodCIDRList:
      - "10.45.0.0/16"