apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trilium
spec:
  tls:
    - hosts:
        - notes.sigurs.io
      secretName: trilium-tls
  rules:
    - host: notes.sigurs.io
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: http
              port:
                name: http